services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto/config/mosquitto.conf
    entrypoint: /docker-entrypoint.sh
    volumes:
      - /home/user/mosquitto/config:/mosquitto/config
      - /home/user/mosquitto/data:/mosquitto/data
      - /home/user/mosquitto/log:/mosquitto/log
    network_mode: bridge
    restart: unless-stopped
  mosquittoapi:
    container_name: mosquittoapi
    image: ghcr.io/pablogrb/mosquittoapi:latest
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    ports:
      - "8000:8000"
    network_mode: bridge
    restart: unless-stopped